# https://docs.docker.com/compose/compose-file/#compose-file-structure-and-examples
version: '3.4'

networks:
  frontend:
  backend:

volumes:
  nginx-logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.16.18.11,rw
      device: ":/docker01_mcA/docker/volumes/wordpress/nginx-logs"

  wordpress-code:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.16.18.11,rw
      device: ":/docker01_mcA/docker/volumes/wordpress/wordpress-code"
  
  wordpress-content:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.16.18.11,rw
      device: ":/docker01_mcA/docker/volumes/wordpress/wordpress-content"

  wordpress-uploads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.16.18.11,rw
      device: ":/docker01_mcA/docker/volumes/wordpress/wordpress-uploads"


  #mariadb-data0:
  #  driver: local

  #! mariadb'nin Dockerfile dosyasında (https://hub.docker.com/_/mariadb/)
  #! "chown -R mysql:mysql /var/lib/mysql"
  #! komutu netapp nfs diskindeki ".snapshot" dizinini değiştiremediği için hata:
  #! "chown: changing ownership of '/var/lib/mysql/.snapshot': read-only file system"
  #! verip container çalışmıyor.
  #! normalde netapp diskindeki ".snapshot" dizinini görmemesi lazım...
  #mariadb-data:
  #  driver: local
  #  driver_opts:
  #    type: nfs
  #    o: addr=172.16.18.11,rw
  #    device: ":/docker01_mcA/docker/volumes/wordpress/mariadb-data"


services:
  nginx:
    image: nginx:1.13
    volumes:
        - /dockernfs/docker/stack/wordpress/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        # - wordpress-code:/var/www/html
        - type: volume
          source: wordpress-code
          target: /var/www/html
          volume:
             nocopy: true
        # - "${PWD}/code/wp-content:/var/www/html/wp-content"
        - type: volume
          source: wordpress-content
          target: /var/www/html/wp-content
          volume:
             nocopy: true

        # - "${PWD}/uploads:/var/www/html/wp-content/uploads"
        - type: volume
          source: wordpress-uploads
          target: /var/www/html/wp-content/uploads
          volume:
             nocopy: true   
     
        # - "${PWD}/logs/nginx:/var/log/nginx"
        - type: volume
          source: nginx-logs
          target: /var/log/nginx
          volume:
             nocopy: true

    ports:
        - "80:80"
        - "443:443"
    networks:
        - frontend
    depends_on:
        - wordpress
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  wordpress:
    image: wordpress:4.9-php7.2-fpm
    # ports:
        # - '9000:9000'
    volumes:
        # - wordpress-code:/var/www/html
        - type: volume
          source: wordpress-code
          target: /var/www/html
          volume:
             nocopy: true
        # - ${PWD}/code/wordpress.4.9:/var/www/html
        # - "${PWD}/code/wp-content:/var/www/html/wp-content"
        - type: volume
          source: wordpress-content
          target: /var/www/html/wp-content
          volume:
             nocopy: true

        # - "${PWD}/uploads:/var/www/html/wp-content/uploads"
        - type: volume
          source: wordpress-uploads
          target: /var/www/html/wp-content/uploads
          volume:
             nocopy: true

    environment:
        - WORDPRESS_DB_NAME=wpdbs
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=database
        - WORDPRESS_DB_PASSWORD=aqwe123
    networks:
        - frontend
        - backend
    depends_on:
        - database
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  database:
    image: mariadb:10.2
    # ports:
        # - '3306:3306'
    volumes:
        # - mariadb-data0:/var/lib/mysql
         - /dockernfs/docker/volumes/wordpress/mariadb-data/:/var/lib/mysql:rw
        # - type: volume
        #   source: mariadb-data
        #   target: /var/lib/mysql/wpdb
        #   volume:
        #      nocopy: true

    environment:
        - MYSQL_ROOT_PASSWORD=aqwe123
    networks:
        - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9070:80
    networks:
      - backend
    depends_on:
      - database
    environment:
        - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
